#!/usr/bin/env python3
"""Worm → crown (worm wheel) geometry calculator.

Takes an existing mating worm as entry data and derives the matching
worm-wheel (crown) blank and tooth parameters.

Correction vs drawing WW-150T-2.0-01 Rev A
------------------------------------------
Rev A computed center distance from the worm *major* diameter:

    a = (d_a1 + d2) / 2 = (28.00 + 303.15) / 2 = 165.58 mm   ← incorrect

The correct relation uses the worm *pitch* diameter d1:

    m  = P_x / π
    d1 = d_a1 − 2·m          (standard addendum h_a1 = m)
    d2 = m · z2
    a  = (d1 + d2) / 2

That also restores consistency with the stated lead angle
λ ≈ arctan(L / (π·d1)) ≈ 4.8°.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass(frozen=True)
class WormInput:
    """Existing mating worm (entry / given data)."""

    major_diameter_mm: float = 28.00  # d_a1 tip / outside
    root_diameter_mm: float = 19.33  # d_f1
    axial_pitch_mm: float = 6.35  # P_x
    starts: int = 1  # z1
    pressure_angle_deg: float = 20.0


@dataclass(frozen=True)
class WheelBlankInput:
    """Non-tooth mechanical features of the crown blank."""

    teeth: int = 150  # z2
    face_width_mm: float = 35.0
    face_width_tol_plus: float = 0.20
    face_width_tol_minus: float = 0.0
    total_width_mm: float = 65.0
    hub_diameter_mm: float = 120.0
    bore_diameter_mm: float = 60.0
    bore_tol_plus: float = 0.03
    bore_tol_minus: float = 0.0
    hub_length_mm: float = 30.0
    keyway: str = "18 × 11 × 70 DIN 6885-1"
    keyway_width: str = "18 P9"
    keyway_depth: str = "11 P9"
    material: str = "Bronze / CuSn12"
    center_distance_tol_mm: float = 0.05


def calculate_crown(
    worm: WormInput | None = None,
    blank: WheelBlankInput | None = None,
) -> dict:
    """Derive crown geometry from mating-worm entry data."""
    worm = worm or WormInput()
    blank = blank or WheelBlankInput()

    px = worm.axial_pitch_mm
    z1 = worm.starts
    z2 = blank.teeth
    da1 = worm.major_diameter_mm
    df1 = worm.root_diameter_mm

    # Axial module from worm axial pitch
    m = px / math.pi
    p = px  # wheel circular pitch equals worm axial pitch
    lead = z1 * px
    ratio = z2 / z1

    # Recover worm pitch diameter from tip + standard addendum h_a1 = m
    ha1 = m
    d1 = da1 - 2.0 * ha1
    hf1 = (d1 - df1) / 2.0
    q = d1 / m
    lambda_deg = math.degrees(math.atan(lead / (math.pi * d1)))

    # Wheel (crown) — standard proportions, form generated by mating worm
    d2 = m * z2
    ha2 = m
    hf2 = 1.2 * m
    whole_depth = ha2 + hf2
    da2 = d2 + 2.0 * ha2
    df2 = d2 - 2.0 * hf2
    tooth_thickness = p / 2.0  # at pitch circle, zero backlash
    center_distance = (d1 + d2) / 2.0

    # Document Rev A error for the drawing revision note
    a_rev_a = 165.58  # value published on WW-150T-2.0-01 Rev A

    return {
        "worm_input": asdict(worm),
        "blank_input": asdict(blank),
        "worm_derived": {
            "pitch_diameter_d1_mm": d1,
            "addendum_ha1_mm": ha1,
            "dedendum_hf1_mm": hf1,
            "diameter_quotient_q": q,
            "lead_L_mm": lead,
            "lead_angle_lambda_deg": lambda_deg,
        },
        "wheel": {
            "teeth_z2": z2,
            "module_m_mm": m,
            "axial_pitch_Px_mm": px,
            "circular_pitch_p_mm": p,
            "pitch_diameter_d_mm": d2,
            "outside_diameter_da_mm": da2,
            "root_diameter_df_mm": df2,
            "addendum_ha_mm": ha2,
            "dedendum_hf_mm": hf2,
            "whole_depth_h_mm": whole_depth,
            "tooth_thickness_s_mm": tooth_thickness,
            "center_distance_a_mm": center_distance,
            "reduction_ratio_i": ratio,
            "worm_lead_L_mm": lead,
            "lead_angle_lambda_deg": lambda_deg,
            "pressure_angle_deg": worm.pressure_angle_deg,
        },
        "display": {
            # Rounded values for the engineering drawing
            "m": round(m, 3),
            "Px": round(px, 3),
            "p": round(p, 3),
            "d": round(d2, 2),
            "da": round(da2, 2),
            "df": round(df2, 2),
            "ha": round(ha2, 2),
            "hf": round(hf2, 2),
            "h": round(whole_depth, 2),
            "s": round(tooth_thickness, 3),
            "a": round(center_distance, 2),
            "d1": round(d1, 2),
            "lambda_deg": round(lambda_deg, 1),
            "q": round(q, 3),
            "i_label": f"{z2}:{z1}",
            "L": round(lead, 2),
        },
        "revision": {
            "drawing_no": "WW-150T-2.0-01",
            "rev": "B",
            "prev_rev": "A",
            "a_revA_mm": a_rev_a,
            "a_revB_mm": round(center_distance, 2),
            "delta_a_mm": round(a_rev_a - center_distance, 2),
            "fix": (
                "Center distance uses worm pitch diameter "
                "d1 = da1 − 2m, not major diameter da1."
            ),
        },
    }


def _round_floats(obj, ndigits: int = 6):
    if isinstance(obj, float):
        return round(obj, ndigits)
    if isinstance(obj, dict):
        return {k: _round_floats(v, ndigits) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_round_floats(v, ndigits) for v in obj]
    return obj


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Calculate worm-wheel (crown) geometry from mating worm data."
    )
    parser.add_argument("--da1", type=float, default=28.00, help="Worm major diameter [mm]")
    parser.add_argument("--df1", type=float, default=19.33, help="Worm root diameter [mm]")
    parser.add_argument("--Px", type=float, default=6.35, help="Worm axial pitch [mm]")
    parser.add_argument("--z1", type=int, default=1, help="Worm starts")
    parser.add_argument("--z2", type=int, default=150, help="Wheel teeth")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent / "output" / "crown_calc_revB.json",
    )
    args = parser.parse_args()

    result = calculate_crown(
        WormInput(
            major_diameter_mm=args.da1,
            root_diameter_mm=args.df1,
            axial_pitch_mm=args.Px,
            starts=args.z1,
        ),
        WheelBlankInput(teeth=args.z2),
    )
    result = _round_floats(result)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")

    d = result["display"]
    rev = result["revision"]
    print(f"Module m           = {d['m']} mm")
    print(f"Worm pitch dia d1  = {d['d1']} mm  (from da1 − 2m)")
    print(f"Wheel pitch dia d  = {d['d']} mm")
    print(f"Outside dia da     = {d['da']} mm")
    print(f"Root dia df        = {d['df']} mm")
    print(f"Center distance a  = {d['a']} mm   (Rev A was {rev['a_revA_mm']} mm)")
    print(f"Lead angle λ       = {d['lambda_deg']}°")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
