#!/usr/bin/env python3
"""Generate corrected worm-wheel (crown) engineering drawing WW-150T-2.0-01 Rev B."""

from __future__ import annotations

import math
from pathlib import Path

from reportlab.lib.colors import Color, black, white
from reportlab.lib.pagesizes import A3, landscape
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from calculate_crown import WheelBlankInput, WormInput, calculate_crown

LIGHT_BLUE = Color(0.82, 0.90, 0.96)
HEADER_BLUE = Color(0.15, 0.35, 0.55)
TABLE_ALT = Color(0.93, 0.95, 0.97)
NOTE_BG = Color(1.0, 0.97, 0.88)
FIX_BG = Color(1.0, 0.92, 0.88)
DIM_COLOR = Color(0.55, 0.05, 0.05)
THIN = Color(0.25, 0.25, 0.25)


def _fmt(v: float, n: int = 2) -> str:
    return f"{v:.{n}f}"


def draw_title_block(c: canvas.Canvas, W: float, H: float, rev: dict) -> None:
    x0, y0 = 10 * mm, 10 * mm
    tw, th = W - 20 * mm, 28 * mm
    c.setStrokeColor(black)
    c.setLineWidth(1.2)
    c.rect(x0, y0, tw, th)

    cols = [0.42, 0.18, 0.12, 0.14, 0.14]
    xs = [x0]
    for f in cols[:-1]:
        xs.append(xs[-1] + f * tw)
    for x in xs[1:]:
        c.line(x, y0, x, y0 + th)

    c.setFont("Helvetica-Bold", 11)
    c.drawString(x0 + 3 * mm, y0 + th - 7 * mm, "WORM WHEEL (CROWN) — 150 TEETH")
    c.setFont("Helvetica", 8)
    c.drawString(x0 + 3 * mm, y0 + th - 12 * mm, "Generated by mating worm · Pressure angle 20°")
    c.drawString(x0 + 3 * mm, y0 + 3 * mm, "Material: Bronze / CuSn12 or equivalent")

    labels = [
        (xs[1], "Drawing No."),
        (xs[2], "Rev"),
        (xs[3], "Scale"),
        (xs[4], "Date"),
    ]
    values = [
        (xs[1], rev["drawing_no"]),
        (xs[2], rev["rev"]),
        (xs[3], "1:2"),
        (xs[4], "2026-07-09"),
    ]
    for x, lab in labels:
        c.setFont("Helvetica", 6)
        c.setFillColor(THIN)
        c.drawString(x + 2 * mm, y0 + th - 5 * mm, lab)
    c.setFillColor(black)
    for x, val in values:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x + 2 * mm, y0 + th - 14 * mm, val)

    c.setFont("Helvetica", 6.5)
    c.drawString(xs[1] + 2 * mm, y0 + 8 * mm, "Tolerances: ISO 2768-mK")
    c.drawString(xs[1] + 2 * mm, y0 + 3.5 * mm, "Projection: Third Angle")
    c.drawString(xs[3] + 2 * mm, y0 + 3.5 * mm, "All dims in mm")


def draw_boxed_table(
    c: canvas.Canvas,
    x: float,
    y_top: float,
    w: float,
    title: str,
    rows: list[tuple[str, str]],
    header_fill=HEADER_BLUE,
) -> float:
    """Draw a titled parameter table. Returns y at bottom."""
    row_h = 5.2 * mm
    title_h = 6.5 * mm
    h = title_h + len(rows) * row_h

    c.setFillColor(header_fill)
    c.setStrokeColor(black)
    c.setLineWidth(0.8)
    c.rect(x, y_top - title_h, w, title_h, fill=1, stroke=1)
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(x + 2 * mm, y_top - 4.5 * mm, title)

    y = y_top - title_h
    for i, (lab, val) in enumerate(rows):
        y -= row_h
        c.setFillColor(TABLE_ALT if i % 2 else white)
        c.rect(x, y, w, row_h, fill=1, stroke=1)
        c.setFillColor(black)
        c.setFont("Helvetica", 7)
        c.drawString(x + 2 * mm, y + 1.6 * mm, lab)
        c.setFont("Helvetica-Bold", 7)
        c.drawRightString(x + w - 2 * mm, y + 1.6 * mm, val)
    return y


def draw_notes_box(c: canvas.Canvas, x: float, y_top: float, w: float, notes: list[str]) -> float:
    title_h = 6 * mm
    line_h = 4.2 * mm
    h = title_h + len(notes) * line_h + 2 * mm
    y_bot = y_top - h

    c.setFillColor(NOTE_BG)
    c.setStrokeColor(black)
    c.setLineWidth(0.8)
    c.rect(x, y_bot, w, h, fill=1, stroke=1)
    c.setFillColor(HEADER_BLUE)
    c.rect(x, y_top - title_h, w, title_h, fill=1, stroke=1)
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(x + 2 * mm, y_top - 4.2 * mm, "GENERAL NOTES")

    c.setFillColor(black)
    c.setFont("Helvetica", 6.5)
    yy = y_top - title_h - 3.5 * mm
    for n in notes:
        c.drawString(x + 2 * mm, yy, n)
        yy -= line_h
    return y_bot


def draw_fix_banner(c: canvas.Canvas, x: float, y_top: float, w: float, rev: dict) -> float:
    h = 18 * mm
    y_bot = y_top - h
    c.setFillColor(FIX_BG)
    c.setStrokeColor(Color(0.7, 0.2, 0.1))
    c.setLineWidth(1.0)
    c.rect(x, y_bot, w, h, fill=1, stroke=1)
    c.setFillColor(Color(0.55, 0.05, 0.05))
    c.setFont("Helvetica-Bold", 8)
    c.drawString(x + 2 * mm, y_top - 5 * mm, "REVISION B — CALCULATION FIX")
    c.setFont("Helvetica", 6.5)
    c.setFillColor(black)
    lines = [
        f"Rev A used a = (da1 + d)/2 = ({_fmt(28.0)} + {_fmt(303.15)})/2 = {_fmt(rev['a_revA_mm'])} mm (worm MAJOR dia).",
        f"Rev B uses a = (d1 + d)/2 with d1 = da1 − 2m = {_fmt(rev.get('d1', 23.96))} mm → a = {_fmt(rev['a_revB_mm'])} mm.",
        f"Δa = −{_fmt(rev['delta_a_mm'])} mm. Lead angle λ ≈ {_fmt(rev.get('lambda', 4.8), 1)}° now consistent with d1.",
    ]
    yy = y_top - 9 * mm
    for line in lines:
        c.drawString(x + 2 * mm, yy, line)
        yy -= 3.5 * mm
    return y_bot


def draw_center_distance_diagram(
    c: canvas.Canvas, cx: float, cy: float, d: dict, blank: dict
) -> None:
    """Schematic worm + wheel mesh with corrected center distance."""
    scale = 0.28  # mm drawing / mm real (compact schematic)
    r_wheel = (d["d"] / 2) * scale
    r_worm = (d["d1"] / 2) * scale
    a_draw = (d["a"]) * scale

    # Wheel pitch circle
    c.setStrokeColor(black)
    c.setLineWidth(1.0)
    c.setDash(3, 2)
    c.circle(cx, cy, r_wheel)
    c.setDash()
    c.setLineWidth(0.7)
    c.circle(cx, cy, (d["da"] / 2) * scale)
    c.setDash(1, 2)
    c.circle(cx, cy, (d["df"] / 2) * scale)
    c.setDash()

    # Worm (to the right)
    wx = cx + a_draw
    c.setLineWidth(1.0)
    c.setDash(3, 2)
    c.circle(wx, cy, r_worm)
    c.setDash()
    c.setLineWidth(0.7)
    c.circle(wx, cy, (28.0 / 2) * scale)  # major
    c.setDash(1, 2)
    c.circle(wx, cy, (19.33 / 2) * scale)
    c.setDash()

    # Centers
    c.setFillColor(black)
    c.circle(cx, cy, 1.2, fill=1, stroke=0)
    c.circle(wx, cy, 1.2, fill=1, stroke=0)

    # Center distance dimension
    c.setStrokeColor(DIM_COLOR)
    c.setFillColor(DIM_COLOR)
    c.setLineWidth(0.6)
    ydim = cy - r_wheel - 8 * mm
    c.line(cx, cy, cx, ydim)
    c.line(wx, cy, wx, ydim)
    c.line(cx, ydim, wx, ydim)
    # arrows
    for x in (cx, wx):
        c.line(x, ydim, x + 2 * mm, ydim + 1.2 * mm)
        c.line(x, ydim, x + 2 * mm, ydim - 1.2 * mm)
        c.line(x, ydim, x - 2 * mm, ydim + 1.2 * mm)
        c.line(x, ydim, x - 2 * mm, ydim - 1.2 * mm)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(
        (cx + wx) / 2,
        ydim - 4 * mm,
        f"a = {_fmt(d['a'])} ± {_fmt(blank['center_distance_tol_mm'], 2)}",
    )
    c.setFont("Helvetica", 6.5)
    c.setFillColor(black)
    c.drawCentredString(cx, cy + r_wheel + 3 * mm, "WHEEL (pitch)")
    c.drawCentredString(wx, cy + r_worm + 8 * mm, "WORM")
    c.setFont("Helvetica", 6)
    c.drawCentredString(wx, cy + r_worm + 4.5 * mm, f"d1={_fmt(d['d1'])}")


def draw_front_view(c: canvas.Canvas, cx: float, cy: float, d: dict) -> None:
    """Front view of wheel face — diameters."""
    scale = 0.38  # 1:2.6-ish for fit
    ra = (d["da"] / 2) * scale
    rp = (d["d"] / 2) * scale
    rf = (d["df"] / 2) * scale
    rbore = (60 / 2) * scale
    rhub = (120 / 2) * scale

    c.setStrokeColor(black)
    c.setLineWidth(1.1)
    c.circle(cx, cy, ra)
    c.setDash(4, 2)
    c.setLineWidth(0.7)
    c.circle(cx, cy, rp)
    c.setDash(1.5, 1.5)
    c.circle(cx, cy, rf)
    c.setDash()
    c.setLineWidth(0.9)
    c.circle(cx, cy, rhub)
    c.circle(cx, cy, rbore)

    # Keyway hint
    kw = 18 * scale / 2
    kd = 11 * scale
    c.rect(cx - kw, cy + rbore - 0.5, 2 * kw, kd, fill=0, stroke=1)

    # Centerlines
    c.setDash([6, 2, 1, 2], 0)
    c.setLineWidth(0.4)
    c.line(cx - ra - 5 * mm, cy, cx + ra + 5 * mm, cy)
    c.line(cx, cy - ra - 5 * mm, cx, cy + ra + 5 * mm)
    c.setDash()

    # Diameter labels on the right
    c.setFillColor(DIM_COLOR)
    c.setStrokeColor(DIM_COLOR)
    c.setLineWidth(0.5)
    x_dim = cx + ra + 4 * mm
    for r, label in (
        (ra, f"Ø {_fmt(d['da'])}  da"),
        (rp, f"Ø {_fmt(d['d'])}  d"),
        (rf, f"Ø {_fmt(d['df'])}  df"),
    ):
        c.line(cx + r, cy, x_dim + 22 * mm, cy + (r - rp) * 0.15)
        c.setFont("Helvetica", 6.5)
        c.drawString(x_dim, cy + (r - rp) * 0.15 - 1 * mm, label)

    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(cx, cy - ra - 6 * mm, "FRONT VIEW  (Scale ≈ 1:2.6)")


def draw_side_view(c: canvas.Canvas, x0: float, y0: float, blank: dict, d: dict) -> None:
    """Side / profile view with face width and hub."""
    scale = 0.55
    face = blank["face_width_mm"] * scale
    total = blank["total_width_mm"] * scale
    hub_len = blank["hub_length_mm"] * scale
    od = d["da"] * scale
    hub_d = blank["hub_diameter_mm"] * scale
    bore = blank["bore_diameter_mm"] * scale

    # Rim body
    c.setStrokeColor(black)
    c.setLineWidth(1.0)
    # Face (tooth rim)
    c.rect(x0, y0, face, od, fill=0, stroke=1)
    # Hub extending left
    hub_y = y0 + (od - hub_d) / 2
    c.rect(x0 - hub_len, hub_y, hub_len, hub_d, fill=0, stroke=1)
    # Bore
    bore_y = y0 + (od - bore) / 2
    c.setDash(2, 2)
    c.rect(x0 - hub_len, bore_y, hub_len + face, bore, fill=0, stroke=1)
    c.setDash()

    # Pitch / root / tip lines on face
    for dia, dash in ((d["d"], (4, 2)), (d["df"], (1.5, 1.5))):
        yy = y0 + (od - dia * scale) / 2
        c.setDash(*dash)
        c.setLineWidth(0.5)
        c.line(x0, yy, x0 + face, yy)
        c.line(x0, yy + dia * scale, x0 + face, yy + dia * scale)
    c.setDash()

    # Dimensions
    c.setStrokeColor(DIM_COLOR)
    c.setFillColor(DIM_COLOR)
    c.setLineWidth(0.5)
    # Face width
    ydim = y0 - 6 * mm
    c.line(x0, y0, x0, ydim)
    c.line(x0 + face, y0, x0 + face, ydim)
    c.line(x0, ydim, x0 + face, ydim)
    c.setFont("Helvetica", 6.5)
    c.drawCentredString(
        x0 + face / 2,
        ydim - 3.5 * mm,
        f"{_fmt(blank['face_width_mm'], 0)} +{_fmt(blank['face_width_tol_plus'], 2)} / −{_fmt(blank['face_width_tol_minus'], 0)}",
    )
    # Total width
    ydim2 = y0 - 12 * mm
    c.line(x0 - hub_len, y0, x0 - hub_len, ydim2)
    c.line(x0 + face, y0, x0 + face, ydim2)
    c.line(x0 - hub_len, ydim2, x0 + face, ydim2)
    c.drawCentredString(x0 + (face - hub_len) / 2, ydim2 - 3.5 * mm, f"{_fmt(blank['total_width_mm'], 0)} (total)")

    # Hub / bore labels
    c.setFillColor(black)
    c.setFont("Helvetica", 6.5)
    c.drawString(x0 - hub_len, hub_y + hub_d + 2 * mm, f"Ø {_fmt(blank['hub_diameter_mm'], 0)} hub")
    c.drawString(
        x0 - hub_len,
        bore_y - 4 * mm,
        f"Ø {_fmt(blank['bore_diameter_mm'], 0)} H7 (+{_fmt(blank['bore_tol_plus'], 2)}/0)",
    )

    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(x0 + face / 2 - hub_len / 2, y0 - 18 * mm, "SIDE VIEW")


def draw_section_aa(c: canvas.Canvas, x0: float, y0: float, d: dict) -> None:
    """Tooth depth callouts (section A-A schematic)."""
    scale = 8.0
    ha = d["ha"] * scale
    hf = d["hf"] * scale
    w = 28 * mm

    c.setStrokeColor(black)
    c.setLineWidth(1.0)
    # Pitch line
    c.setDash(4, 2)
    c.line(x0, y0, x0 + w, y0)
    c.setDash()
    # Tip
    c.line(x0, y0 + ha, x0 + w, y0 + ha)
    # Root
    c.line(x0, y0 - hf, x0 + w, y0 - hf)

    # Tooth sketch
    c.setLineWidth(0.9)
    tooth_w = d["s"] * scale
    pts = [
        (x0 + 6 * mm, y0 - hf),
        (x0 + 8 * mm, y0 + ha),
        (x0 + 8 * mm + tooth_w, y0 + ha),
        (x0 + 10 * mm + tooth_w, y0 - hf),
    ]
    p = c.beginPath()
    p.moveTo(*pts[0])
    for pt in pts[1:]:
        p.lineTo(*pt)
    c.drawPath(p)

    c.setStrokeColor(DIM_COLOR)
    c.setFillColor(DIM_COLOR)
    c.setLineWidth(0.5)
    xd = x0 + w + 2 * mm
    c.line(xd, y0, xd, y0 + ha)
    c.line(xd, y0, xd, y0 - hf)
    c.setFont("Helvetica", 6.5)
    c.drawString(xd + 1.5 * mm, y0 + ha / 2 - 1 * mm, f"ha = {_fmt(d['ha'])}")
    c.drawString(xd + 1.5 * mm, y0 - hf / 2 - 1 * mm, f"hf = {_fmt(d['hf'])}")
    c.drawString(xd + 1.5 * mm, y0 - hf - 5 * mm, f"h = {_fmt(d['h'])}")

    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(x0, y0 - hf - 10 * mm, "SECTION A–A  (tooth depth)")
    c.setFont("Helvetica", 6)
    c.drawString(x0, y0 - hf - 13.5 * mm, f"Keyway: {WheelBlankInput().keyway}")


def build_drawing(path: Path) -> dict:
    result = calculate_crown()
    d = result["display"]
    blank = result["blank_input"]
    rev = dict(result["revision"])
    rev["d1"] = d["d1"]
    rev["lambda"] = d["lambda_deg"]

    W, H = landscape(A3)
    c = canvas.Canvas(str(path), pagesize=landscape(A3))
    c.setTitle(f"{rev['drawing_no']} Rev {rev['rev']} — Worm Wheel Crown")
    c.setAuthor("Worm crown calculator")

    # Outer border
    c.setLineWidth(1.5)
    c.rect(8 * mm, 8 * mm, W - 16 * mm, H - 16 * mm)
    c.setLineWidth(0.5)
    c.rect(10 * mm, 10 * mm, W - 20 * mm, H - 20 * mm)

    # Header
    c.setFillColor(HEADER_BLUE)
    c.rect(10 * mm, H - 22 * mm, W - 20 * mm, 12 * mm, fill=1, stroke=1)
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(14 * mm, H - 17 * mm, "WORM WHEEL (CROWN) — ENGINEERING DRAWING")
    c.setFont("Helvetica", 9)
    c.drawRightString(W - 14 * mm, H - 17 * mm, f"{rev['drawing_no']}  ·  REV {rev['rev']}")

    # --- Left column: mating worm + tooth data + blank ---
    left_x = 14 * mm
    y = H - 28 * mm

    y = draw_boxed_table(
        c,
        left_x,
        y,
        72 * mm,
        "MATING WORM DATA (EXISTING — ENTRY)",
        [
            ("Major diameter da1", f"{_fmt(result['worm_input']['major_diameter_mm'])} mm"),
            ("Root diameter df1", f"{_fmt(result['worm_input']['root_diameter_mm'])} mm"),
            ("Axial pitch Px", f"{_fmt(result['worm_input']['axial_pitch_mm'], 3)} mm"),
            ("Starts z1", f"{result['worm_input']['starts']}"),
            ("Pitch diameter d1 (derived)", f"{_fmt(d['d1'])} mm"),
            ("Lead L = z1·Px", f"{_fmt(d['L'])} mm"),
            ("Lead angle λ", f"≈ {_fmt(d['lambda_deg'], 1)}°"),
            ("Diameter quotient q = d1/m", f"{_fmt(d['q'], 3)}"),
        ],
    )

    y -= 4 * mm
    y = draw_boxed_table(
        c,
        left_x,
        y,
        72 * mm,
        "TOOTH DATA (REFERENCE)",
        [
            ("Module m = Px/π", f"{_fmt(d['m'], 3)} mm"),
            ("Pressure angle", f"{_fmt(result['worm_input']['pressure_angle_deg'], 0)}°"),
            ("Axial pitch Px", f"{_fmt(d['Px'], 3)} mm"),
            ("Worm starts z1", f"{result['worm_input']['starts']}"),
            ("Wheel teeth z2", f"{blank['teeth']}"),
        ],
    )

    y -= 4 * mm
    y = draw_boxed_table(
        c,
        left_x,
        y,
        72 * mm,
        "RECOMMENDED BLANK (BEFORE CUTTING)",
        [
            ("Outside diameter", f"{_fmt(d['da'], 1)} mm"),
            ("Face width", f"{_fmt(blank['face_width_mm'], 0)} mm"),
            ("Bore", f"{_fmt(blank['bore_diameter_mm'], 0)} mm H7"),
            ("Hub diameter", f"{_fmt(blank['hub_diameter_mm'], 0)} mm"),
            ("Hub length", f"{_fmt(blank['hub_length_mm'], 0)} mm"),
            ("Material", blank["material"]),
        ],
    )

    y -= 4 * mm
    notes = [
        "1. Pressure angle: 20° (standard).",
        "2. Tooth form generated by mating worm.",
        "3. All dimensions in millimeters.",
        "4. Unspecified fillet radius = 1.5 mm.",
        "5. Deburr all edges 0.2 × 45°.",
        "6. Material: Bronze (CuSn12) or equivalent.",
        "7. Heat treatment (if required) after machining.",
        "8. REV B: center distance uses worm pitch dia d1.",
    ]
    y = draw_notes_box(c, left_x, y, 72 * mm, notes)

    # --- Right column: wheel parameters ---
    right_x = W - 14 * mm - 78 * mm
    y = H - 28 * mm
    y = draw_boxed_table(
        c,
        right_x,
        y,
        78 * mm,
        "WORM WHEEL PARAMETERS (CORRECTED)",
        [
            ("Number of teeth z2", f"{blank['teeth']}"),
            ("Module m (from Px)", f"{_fmt(d['m'], 3)} mm"),
            ("Axial pitch Px", f"{_fmt(d['Px'], 3)} mm"),
            ("Circular pitch p", f"{_fmt(d['p'], 3)} mm"),
            ("Pitch diameter d", f"{_fmt(d['d'])} mm"),
            ("Outside diameter da", f"{_fmt(d['da'])} mm"),
            ("Root diameter df", f"{_fmt(d['df'])} mm"),
            ("Addendum ha", f"{_fmt(d['ha'])} mm"),
            ("Dedendum hf", f"{_fmt(d['hf'])} mm"),
            ("Whole depth h", f"{_fmt(d['h'])} mm"),
            ("Tooth thickness s (pitch)", f"{_fmt(d['s'], 3)} mm"),
            ("Center distance a", f"{_fmt(d['a'])} mm"),
            ("Reduction ratio i = z2/z1", d["i_label"]),
            ("Worm lead L = z1·Px", f"{_fmt(d['L'])} mm"),
            ("Estimated lead angle λ", f"≈ {_fmt(d['lambda_deg'], 1)}°"),
        ],
    )

    y -= 4 * mm
    draw_fix_banner(c, right_x, y, 78 * mm, rev)

    # --- Center graphics ---
    mid_x = W / 2
    draw_center_distance_diagram(c, mid_x - 25 * mm, H - 95 * mm, d, blank)
    c.setFont("Helvetica-Oblique", 7)
    c.setFillColor(THIN)
    c.drawCentredString(mid_x, H - 55 * mm, "CENTER DISTANCE (corrected — pitch diameters)")

    draw_front_view(c, mid_x - 15 * mm, 95 * mm, d)
    draw_side_view(c, mid_x + 55 * mm, 70 * mm, blank, d)
    draw_section_aa(c, mid_x + 55 * mm, 175 * mm, d)

    # Keyway detail box
    kx, ky = 14 * mm, 42 * mm
    c.setStrokeColor(black)
    c.setLineWidth(0.8)
    c.setFillColor(LIGHT_BLUE)
    c.rect(kx, ky, 55 * mm, 28 * mm, fill=1, stroke=1)
    c.setFillColor(black)
    c.setFont("Helvetica-Bold", 7)
    c.drawString(kx + 2 * mm, ky + 22 * mm, "KEYWAY DETAIL")
    c.setFont("Helvetica", 6.5)
    c.drawString(kx + 2 * mm, ky + 16 * mm, f"Width:  {WheelBlankInput().keyway_width}")
    c.drawString(kx + 2 * mm, ky + 11 * mm, f"Depth:  {WheelBlankInput().keyway_depth}")
    c.drawString(kx + 2 * mm, ky + 6 * mm, "(from top of bore)")
    c.drawString(kx + 2 * mm, ky + 2 * mm, WheelBlankInput().keyway)

    draw_title_block(c, W, H, rev)

    # Formulas strip above title block
    c.setFont("Helvetica", 6.5)
    c.setFillColor(THIN)
    c.drawString(
        14 * mm,
        40 * mm,
        "Formulas:  m = Px/π ·  d1 = da1 − 2m ·  d = m·z2 ·  a = (d1 + d)/2 ·  λ = arctan(L/(π·d1)) ·  ha = m ·  hf = 1.2m",
    )

    c.showPage()
    c.save()
    return result


def main() -> None:
    out_dir = Path(__file__).resolve().parent / "drawings"
    out_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = out_dir / "WW-150T-2.0-01_RevB.pdf"
    result = build_drawing(pdf_path)

    # Also emit a lightweight SVG companion for quick preview
    svg_path = out_dir / "WW-150T-2.0-01_RevB.svg"
    d = result["display"]
    rev = result["revision"]
    svg = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1100" viewBox="0 0 1600 1100">
  <rect width="1600" height="1100" fill="#f7f7f4"/>
  <rect x="20" y="20" width="1560" height="1060" fill="none" stroke="#222" stroke-width="3"/>
  <rect x="20" y="20" width="1560" height="56" fill="#24558c"/>
  <text x="40" y="55" fill="#fff" font-family="Helvetica, Arial, sans-serif" font-size="26" font-weight="bold">
    WORM WHEEL (CROWN) — {rev['drawing_no']} REV {rev['rev']}
  </text>
  <text x="40" y="110" font-family="Helvetica, Arial, sans-serif" font-size="16" fill="#222">
    Corrected from mating worm entry data (da1={result['worm_input']['major_diameter_mm']},
    df1={result['worm_input']['root_diameter_mm']}, Px={result['worm_input']['axial_pitch_mm']}, z1={result['worm_input']['starts']})
  </text>
  <rect x="40" y="130" width="520" height="200" fill="#ffebe6" stroke="#a33" stroke-width="2"/>
  <text x="55" y="155" font-family="Helvetica, Arial, sans-serif" font-size="16" font-weight="bold" fill="#8b1a1a">REVISION B — CALCULATION FIX</text>
  <text x="55" y="180" font-family="Helvetica, Arial, sans-serif" font-size="13">Rev A: a = (da1 + d)/2 = 165.58 mm  (used worm MAJOR diameter)</text>
  <text x="55" y="205" font-family="Helvetica, Arial, sans-serif" font-size="13">Rev B: a = (d1 + d)/2 = {d['a']} mm  with d1 = da1 − 2m = {d['d1']} mm</text>
  <text x="55" y="230" font-family="Helvetica, Arial, sans-serif" font-size="13">Δa = −{rev['delta_a_mm']} mm · λ ≈ {d['lambda_deg']}° (consistent with pitch diameter)</text>
  <text x="55" y="260" font-family="Helvetica, Arial, sans-serif" font-size="13">m = {d['m']} · d = {d['d']} · da = {d['da']} · df = {d['df']} · ha = {d['ha']} · hf = {d['hf']}</text>
  <text x="55" y="285" font-family="Helvetica, Arial, sans-serif" font-size="13">s = {d['s']} · i = {d['i_label']} · L = {d['L']} · q = {d['q']}</text>

  <!-- schematic -->
  <g transform="translate(900,420)">
    <circle cx="0" cy="0" r="{d['da']/2*0.9}" fill="none" stroke="#222" stroke-width="2"/>
    <circle cx="0" cy="0" r="{d['d']/2*0.9}" fill="none" stroke="#222" stroke-width="1.5" stroke-dasharray="8 4"/>
    <circle cx="0" cy="0" r="{d['df']/2*0.9}" fill="none" stroke="#666" stroke-width="1" stroke-dasharray="3 3"/>
    <circle cx="0" cy="0" r="27" fill="none" stroke="#222" stroke-width="1.5"/>
    <circle cx="{d['a']*0.9}" cy="0" r="{d['d1']/2*0.9}" fill="none" stroke="#222" stroke-width="1.5" stroke-dasharray="6 3"/>
    <circle cx="{d['a']*0.9}" cy="0" r="12.6" fill="none" stroke="#222" stroke-width="1.2"/>
    <line x1="0" y1="160" x2="{d['a']*0.9}" y2="160" stroke="#a11" stroke-width="1.5"/>
    <text x="{d['a']*0.45}" y="185" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="14" fill="#a11" font-weight="bold">a = {d['a']} ± 0.05</text>
    <text x="0" y="-160" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="14">WHEEL</text>
    <text x="{d['a']*0.9}" y="-40" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="14">WORM d1={d['d1']}</text>
  </g>

  <g font-family="Helvetica, Arial, sans-serif" font-size="14" fill="#222">
    <text x="40" y="380" font-weight="bold">WHEEL PARAMETERS</text>
    <text x="40" y="410">z2 = {result['blank_input']['teeth']}</text>
    <text x="40" y="435">m = {d['m']} mm</text>
    <text x="40" y="460">d = {d['d']} mm</text>
    <text x="40" y="485">da = {d['da']} mm</text>
    <text x="40" y="510">df = {d['df']} mm</text>
    <text x="40" y="535">ha / hf / h = {d['ha']} / {d['hf']} / {d['h']} mm</text>
    <text x="40" y="560">s = {d['s']} mm</text>
    <text x="40" y="585" font-weight="bold" fill="#8b1a1a">a = {d['a']} mm  (was 165.58)</text>
    <text x="40" y="610">λ ≈ {d['lambda_deg']}°</text>
    <text x="40" y="650">Face width 35 +0.20/0 · Bore Ø60 H7 · Hub Ø120 · Material CuSn12</text>
  </g>

  <text x="40" y="1040" font-family="Helvetica, Arial, sans-serif" font-size="12" fill="#555">
    Formulas: m=Px/π · d1=da1−2m · d=m·z2 · a=(d1+d)/2 · λ=arctan(L/(π·d1)) · ha=m · hf=1.2m
  </text>
</svg>
"""
    svg_path.write_text(svg)

    # PNG preview via Pillow rasterization of key summary card
    try:
        from PIL import Image, ImageDraw, ImageFont

        img = Image.new("RGB", (1400, 900), (247, 247, 244))
        draw = ImageDraw.Draw(img)
        try:
            font_lg = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 28)
            font_md = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 18)
            font_sm = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 15)
            font_b = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18)
        except OSError:
            font_lg = font_md = font_sm = font_b = ImageFont.load_default()

        draw.rectangle([0, 0, 1400, 70], fill=(36, 85, 140))
        draw.text((24, 18), f"WORM WHEEL (CROWN)  {rev['drawing_no']}  REV {rev['rev']}", fill="white", font=font_lg)

        draw.rectangle([24, 100, 900, 280], fill=(255, 235, 230), outline=(160, 40, 30), width=2)
        draw.text((40, 115), "REVISION B — CALCULATION FIX", fill=(139, 26, 26), font=font_b)
        draw.text((40, 150), "Rev A used worm MAJOR diameter in center distance:", fill=(40, 40, 40), font=font_sm)
        draw.text((40, 175), "    a = (da1 + d)/2 = (28.00 + 303.15)/2 = 165.58 mm   ← incorrect", fill=(40, 40, 40), font=font_sm)
        draw.text((40, 205), "Rev B uses worm PITCH diameter d1 = da1 − 2m:", fill=(40, 40, 40), font=font_sm)
        draw.text((40, 230), f"    d1 = {d['d1']} mm ·  a = (d1 + d)/2 = {d['a']} mm   ← corrected (Δa = −{rev['delta_a_mm']} mm)", fill=(40, 40, 40), font=font_sm)

        # Circles schematic
        cx, cy = 1050, 480
        s = 0.85
        for dia, width, dash in ((d["da"], 3, None), (d["d"], 2, True), (d["df"], 1, True)):
            r = int(dia / 2 * s)
            # Pillow doesn't dash easily; use solid with different colors
            color = (34, 34, 34) if width >= 2 else (100, 100, 100)
            draw.ellipse([cx - r, cy - r, cx + r, cy + r], outline=color, width=width)
        wx = cx + int(d["a"] * s)
        r1 = int(d["d1"] / 2 * s)
        draw.ellipse([wx - r1, cy - r1, wx + r1, cy + r1], outline=(34, 34, 34), width=2)
        draw.ellipse([wx - 14, cy - 14, wx + 14, cy + 14], outline=(34, 34, 34), width=2)
        draw.line([cx, cy + int(d["da"] / 2 * s) + 20, wx, cy + int(d["da"] / 2 * s) + 20], fill=(160, 30, 30), width=2)
        draw.text(((cx + wx) // 2 - 60, cy + int(d["da"] / 2 * s) + 28), f"a = {d['a']} ± 0.05", fill=(160, 30, 30), font=font_b)
        draw.text((cx - 30, cy - int(d["da"] / 2 * s) - 28), "WHEEL", fill=(20, 20, 20), font=font_md)
        draw.text((wx - 50, cy - 50), f"WORM d1={d['d1']}", fill=(20, 20, 20), font=font_sm)

        rows = [
            ("Module m", f"{d['m']} mm"),
            ("Pitch diameter d", f"{d['d']} mm"),
            ("Outside diameter da", f"{d['da']} mm"),
            ("Root diameter df", f"{d['df']} mm"),
            ("Addendum / Dedendum", f"{d['ha']} / {d['hf']} mm"),
            ("Whole depth h", f"{d['h']} mm"),
            ("Tooth thickness s", f"{d['s']} mm"),
            ("Center distance a", f"{d['a']} mm"),
            ("Lead angle λ", f"≈ {d['lambda_deg']}°"),
            ("Reduction i", d["i_label"]),
        ]
        y = 320
        draw.text((40, y), "CORRECTED WHEEL PARAMETERS", fill=(36, 85, 140), font=font_b)
        y += 35
        for lab, val in rows:
            draw.text((40, y), lab, fill=(50, 50, 50), font=font_sm)
            draw.text((320, y), val, fill=(20, 20, 20), font=font_b)
            y += 28

        draw.text((40, 860), "Formulas: m=Px/π · d1=da1−2m · d=m·z2 · a=(d1+d)/2 · λ=arctan(L/(π·d1))", fill=(90, 90, 90), font=font_sm)
        png_path = out_dir / "WW-150T-2.0-01_RevB_preview.png"
        img.save(png_path)
        print(f"Wrote {png_path}")
    except Exception as exc:  # noqa: BLE001
        print(f"PNG preview skipped: {exc}")

    print(f"Wrote {pdf_path}")
    print(f"Wrote {svg_path}")
    print(f"Center distance: {d['a']} mm (was {rev['a_revA_mm']} mm)")


if __name__ == "__main__":
    main()
